default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: magjury  # Remplacez par votre nom d'utilisateur PostgreSQL
  password: 123456  # Remplacez par votre mot de passe PostgreSQL
  host: localhost

development:
  <<: *default
  database: magjury_db  # Nom de la base de données de développement

test:
  <<: *default
  database: magjury_test  # Nom de la base de données de test

production:
  <<: *default
  database: magjury_production  # Nom de la base de données de production
  username: <%= ENV['PRODUCTION_DB_USERNAME'] %>  # Utilisez une variable d'environnement pour le nom d'utilisateur en production
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>  # Utilisez une variable d'environnement pour le mot de passe en production
